-- Ramssol Pre-Sales Copilot: free-tier schema, Auth profile bootstrap,
-- row-level authorization, workflow guardrails, and proposal Realtime.

create schema if not exists private;
revoke all on schema private from public;

create sequence if not exists public.proposal_number_seq as bigint start with 151;
create sequence if not exists public.case_number_seq as bigint start with 94;

create or replace function private.next_proposal_id()
returns text
language sql
volatile
security invoker
set search_path = ''
as $$
  select 'PROP-' || extract(year from current_date)::integer::text || '-' ||
         lpad(nextval('public.proposal_number_seq'::regclass)::text, 6, '0')
$$;

create or replace function private.next_case_id()
returns text
language sql
volatile
security invoker
set search_path = ''
as $$
  select 'CASE-' || extract(year from current_date)::integer::text || '-' ||
         lpad(nextval('public.case_number_seq'::regclass)::text, 6, '0')
$$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null default '',
  last_name text not null default '',
  full_name text not null,
  email text not null unique,
  role text not null default 'Sales Representative',
  level smallint not null default 1 check (level between 1 and 3),
  status text not null default 'active' check (status in ('active', 'inactive')),
  last_active timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.proposals (
  id text primary key default private.next_proposal_id(),
  case_id text not null default private.next_case_id(),
  opportunity_id text not null default '',
  version integer not null default 1 check (version > 0),
  company text not null,
  deal text not null,
  value numeric(14, 2) not null default 0 check (value >= 0),
  submitted_by_id uuid not null default auth.uid() references public.profiles(id),
  submitted_by text not null,
  owner_id uuid not null default auth.uid() references public.profiles(id),
  owner text not null,
  generated_on date not null default current_date,
  submitted_at timestamptz,
  status text not null default 'Draft' check (
    status in ('Draft', 'Pending Review', 'Approved', 'Reject & Revise', 'Reject & Close', 'Superseded')
  ),
  reviewer_id uuid references public.profiles(id),
  reviewer text not null default '',
  reviewed_at timestamptz,
  rejection_reason text not null default '',
  review_note text not null default '',
  sections jsonb not null default '{}'::jsonb check (jsonb_typeof(sections) = 'object'),
  outcome text check (outcome is null or outcome in ('Pending', 'Won', 'Lost')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (case_id, version)
);

create table public.deals (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references public.profiles(id),
  rep text not null,
  account text not null,
  stage smallint not null default 1 check (stage between 1 and 8),
  days_in_stage integer not null default 0 check (days_in_stage >= 0),
  days_to_close integer not null default 0 check (days_to_close >= 0),
  value numeric(14, 2) not null default 0 check (value >= 0),
  movement text not null default '',
  status text not null default 'On Track',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.closed_deals (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references public.profiles(id),
  rep text not null,
  account text not null,
  value numeric(14, 2) not null default 0 check (value >= 0),
  close_date date not null,
  source text not null default '',
  outcome text not null check (outcome in ('Won', 'Lost')),
  loss_reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.prospects (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references public.profiles(id),
  name text not null,
  type text not null default '',
  country text not null default '',
  website text not null default '',
  added_on date not null default current_date,
  tags text[] not null default '{}',
  employees text not null default '',
  opportunities integer not null default 0 check (opportunities >= 0),
  total_value numeric(14, 2) not null default 0 check (total_value >= 0),
  pain_points text[] not null default '{}',
  contact text,
  authority text,
  it_budget text,
  hr_budget text,
  timeline text,
  current_system text,
  current_module text,
  ai_research jsonb check (ai_research is null or jsonb_typeof(ai_research) = 'object'),
  watched boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index proposals_owner_id_idx on public.proposals(owner_id);
create index proposals_status_idx on public.proposals(status);
create index proposals_case_version_idx on public.proposals(case_id, version desc);
create index deals_owner_id_idx on public.deals(owner_id);
create index closed_deals_owner_id_idx on public.closed_deals(owner_id);
create index closed_deals_close_date_idx on public.closed_deals(close_date desc);
create index prospects_owner_id_idx on public.prospects(owner_id);

create or replace function private.current_access_level()
returns smallint
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select p.level from public.profiles as p where p.id = (select auth.uid())),
    0
  )::smallint
$$;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  given_name text := coalesce(new.raw_user_meta_data ->> 'first_name', '');
  family_name text := coalesce(new.raw_user_meta_data ->> 'last_name', '');
  display_name text;
begin
  display_name := nullif(trim(concat_ws(' ', given_name, family_name)), '');
  display_name := coalesce(display_name, split_part(coalesce(new.email, ''), '@', 1), 'User');

  insert into public.profiles (
    id, first_name, last_name, full_name, email, role, level
  ) values (
    new.id,
    given_name,
    family_name,
    display_name,
    coalesce(new.email, new.id::text || '@pending.local'),
    'Sales Representative',
    1
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

create or replace function private.protect_profile_access()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if current_user not in ('postgres', 'service_role', 'supabase_admin') and
     private.current_access_level() < 3 and
     (new.id, new.email, new.role, new.level) is distinct from
     (old.id, old.email, old.role, old.level) then
    raise exception 'Only Level 3 administrators can change profile access.'
      using errcode = '42501';
  end if;
  return new;
end;
$$;

create or replace function private.enforce_proposal_workflow()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  access_level smallint := private.current_access_level();
begin
  if access_level >= 2 or current_user in ('postgres', 'service_role', 'supabase_admin') then
    return new;
  end if;

  if tg_op = 'INSERT' then
    if new.owner_id is distinct from (select auth.uid()) or
       new.submitted_by_id is distinct from (select auth.uid()) or
       new.status not in ('Draft', 'Pending Review') or
       new.reviewer_id is not null or new.reviewer <> '' or
       new.reviewed_at is not null or new.rejection_reason <> '' or
       new.review_note <> '' or new.outcome is not null then
      raise exception 'Level 1 users can only create their own draft or pending proposals.'
        using errcode = '42501';
    end if;
    return new;
  end if;

  if new.owner_id is distinct from old.owner_id or
     new.submitted_by_id is distinct from old.submitted_by_id or
     new.reviewer_id is distinct from old.reviewer_id or
     new.reviewer is distinct from old.reviewer or
     new.reviewed_at is distinct from old.reviewed_at or
     new.rejection_reason is distinct from old.rejection_reason or
     new.review_note is distinct from old.review_note or
     new.outcome is distinct from old.outcome then
    raise exception 'Level 1 users cannot change reviewer-controlled proposal fields.'
      using errcode = '42501';
  end if;

  if not (
    (old.status = 'Draft' and new.status in ('Draft', 'Pending Review')) or
    (old.status = 'Pending Review' and new.status = 'Pending Review') or
    (old.status = 'Reject & Revise' and new.status in ('Reject & Revise', 'Superseded')) or
    (old.status = new.status)
  ) then
    raise exception 'This proposal status transition requires a reviewer.'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger profiles_protect_access
before update on public.profiles
for each row execute function private.protect_profile_access();

create trigger proposals_set_updated_at
before update on public.proposals
for each row execute function private.set_updated_at();

create trigger proposals_enforce_workflow
before insert or update on public.proposals
for each row execute function private.enforce_proposal_workflow();

create trigger deals_set_updated_at
before update on public.deals
for each row execute function private.set_updated_at();

create trigger closed_deals_set_updated_at
before update on public.closed_deals
for each row execute function private.set_updated_at();

create trigger prospects_set_updated_at
before update on public.prospects
for each row execute function private.set_updated_at();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

alter table public.profiles enable row level security;
alter table public.proposals enable row level security;
alter table public.deals enable row level security;
alter table public.closed_deals enable row level security;
alter table public.prospects enable row level security;

create policy "profiles_select_by_level"
on public.profiles for select
to authenticated
using (id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "profiles_update_by_level"
on public.profiles for update
to authenticated
using (id = (select auth.uid()) or private.current_access_level() >= 3)
with check (id = (select auth.uid()) or private.current_access_level() >= 3);

create policy "proposals_select_by_level"
on public.proposals for select
to authenticated
using (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "proposals_insert_by_level"
on public.proposals for insert
to authenticated
with check (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "proposals_update_by_level"
on public.proposals for update
to authenticated
using (owner_id = (select auth.uid()) or private.current_access_level() >= 2)
with check (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "deals_select_by_level"
on public.deals for select
to authenticated
using (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "deals_insert_by_level"
on public.deals for insert
to authenticated
with check (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "deals_update_by_level"
on public.deals for update
to authenticated
using (owner_id = (select auth.uid()) or private.current_access_level() >= 2)
with check (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "deals_delete_by_level"
on public.deals for delete
to authenticated
using (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "closed_deals_select_by_level"
on public.closed_deals for select
to authenticated
using (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "closed_deals_insert_by_level"
on public.closed_deals for insert
to authenticated
with check (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "closed_deals_update_by_level"
on public.closed_deals for update
to authenticated
using (owner_id = (select auth.uid()) or private.current_access_level() >= 2)
with check (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "closed_deals_delete_by_level"
on public.closed_deals for delete
to authenticated
using (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "prospects_select_by_level"
on public.prospects for select
to authenticated
using (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "prospects_insert_by_level"
on public.prospects for insert
to authenticated
with check (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "prospects_update_by_level"
on public.prospects for update
to authenticated
using (owner_id = (select auth.uid()) or private.current_access_level() >= 2)
with check (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create policy "prospects_delete_by_level"
on public.prospects for delete
to authenticated
using (owner_id = (select auth.uid()) or private.current_access_level() >= 2);

create or replace view public.my_proposals
with (security_invoker = true)
as
select *
from public.proposals
where status not in ('Superseded', 'Reject & Close')
  and owner_id = (select auth.uid());

create or replace view public.admin_approvals
with (security_invoker = true)
as
select *
from public.proposals
where status = 'Pending Review';

create or replace view public.proposal_version_history
with (security_invoker = true)
as
select *
from public.proposals
order by case_id, version;

-- New Supabase projects no longer expose new public tables automatically.
-- These grants opt authenticated users into the Data API; RLS still controls rows.
revoke all on public.profiles, public.proposals, public.deals,
  public.closed_deals, public.prospects from anon;
grant select, update on public.profiles to authenticated;
grant select, insert, update on public.proposals to authenticated;
grant select, insert, update, delete on public.deals,
  public.closed_deals, public.prospects to authenticated;
grant select on public.my_proposals, public.admin_approvals,
  public.proposal_version_history to authenticated;
grant usage, select on sequence public.proposal_number_seq,
  public.case_number_seq, public.prospects_id_seq to authenticated;

grant usage on schema private to authenticated;
revoke all on all functions in schema private from public, anon;
grant execute on function private.next_proposal_id() to authenticated;
grant execute on function private.next_case_id() to authenticated;
grant execute on function private.current_access_level() to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'proposals'
  ) then
    alter publication supabase_realtime add table public.proposals;
  end if;
end
$$;

comment on table public.proposals is
  'Immutable proposal-version store. Reject & Revise creates a new row; proposal rows are never deleted.';
comment on view public.my_proposals is
  'Current user proposals excluding Superseded and Reject & Close versions.';
comment on view public.admin_approvals is
  'Team proposal queue filtered to Pending Review; base-table RLS remains in force.';
comment on view public.proposal_version_history is
  'All visible proposal versions ordered by case and version; filter by case_id when querying.';
